#!/bin/sh
# ./.git/hooks/pre-commit-format-shell
# Assumption: npm/yarn has installed the prettier package
# Based on the bash script prescribed at https://prettier.io/docs/en/precommit.html#option-5-bash-script

shfiles=$(git diff --cached --name-only --diff-filter=ACM "*.sh" | tr '\n' ' ')
[ -z "$shfiles" ] && exit 0

# Prettify all staged .js files
echo "💅 Automatically formatting staged Shell files using prettier ($(echo $shfiles | wc -w | awk '{print $1}') total)"
echo "$shfiles" | xargs ./node_modules/.bin/prettier --write --loglevel=error

# Add back the modified/prettified files to staging
echo "$shfiles" | xargs git add

exit 0
