#! /bin/sh

########################################
# Monitor
########################################

# set up the two monitors for bspwm
external_monitor=$(xrandr --query | grep 'DP-1')
if [[ $external_monitor = *disconnected* ]]; then
    external_monitor=$(xrandr --query | grep -w 'DVI-I-2-1')
fi

if [[ ! $external_monitor = *disconnected* ]]; then
    external_monitor=$(echo $external_monitor | cut -d" " -f1)
    echo "Monitor $external_monitor connected"
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output $external_monitor --mode 1920x1080 --rotate normal --right-of eDP-1
    bspc monitor eDP-1 -d 1 2 3 4 5
    bspc monitor $external_monitor -d 6 7 8 9 0
else
    echo "Monitor disconnected"
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output DP-1 --off
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
fi

#bspc wm -O eDP-1 $external_monitor

########################################
# Design
########################################


bspc config border_width         	2
bspc config window_gap          	10
bspc config split_ratio			0.50

bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config single_monocle		false
bspc config focus_follows_pointer	true

bspc config focused_border_color	#81A1C1
bspc config normal_border_color		#2E3440
bspc config active_border_color		#B48EAD
bspc config presel_feedback_color	#A3BE8C

########################################
# Rules
########################################

# Fix for Spotify setting up WM_CLASS too late.
# See https://github.com/baskerville/bspwm/issues/291#issuecomment-265999167
bspc config external_rules_command ${Home}.config/bspwm/scripts/bspwm-rules

bspc rule -a Chromium desktop='^2' border=off
bspc rule -a TelegramDesktop desktop='^5' border=off
bspc rule -a Discord desktop='^5' border=off
bspc rule -a "Microsoft Teams - Preview" desktop='^6' border=off
bspc rule -a code-oss border=off

########################################
# Startup
########################################

# Launch Polybar
${HOME}/.config/polybar/launch.sh

# Launch compositor
killall -qw picom; picom --experimental-backend &

# Launch dunst
/usr/bin/dunst &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Setup wallpaper
feh --no-fehbg --bg-scale ${HOME}/.config/bspwm/wallpapers/Flat-BSPWM.png

# Force reload sxhkd (started in .xinitrc)
pkill -USR1 -x sxhkd
