#! /bin/sh

########################################
# Monitor
########################################

bspc monitor -d 1 2 3 4 5 6 7 8 9

########################################
# Design
########################################

bspc config border_width         	2
#bscp config border_radius		2
bspc config window_gap          	10
bspc config split_ratio			0.50

bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config paddingless_monocle		true
bspc config single_monocle		false
bspc config focus_follows_pointer	true

bscp config focused_border_color	#81A1C1
bscp config normal_border_color		#2E3440
bscp config active_bordel_color		#B48EAD
bscp config presel_feedback_color	#A3BE8C

########################################
# Startup programs
########################################

# Kill if already running
killall -9 sxhkd

# Launch keybindings deamon
sxhkd &

# Launch compositor
picom &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Setup wallpaper
feh --no-fehbg --bg-scale ${HOME}/.config/bspwm/wallpapers/DSCF4661-Enhanced_IG.jpg
#feh --no-fehbg --bg-scale ${HOME}/.config/bspwm/wallpapers/DSCF4640.jpg
#feh --no-fehbg --bg-scale ${HOME}/.config/bspwm/wallpapers/Osaka_Douves.jpg

# Launch Polybar
${HOME}/.config/polybar/launch.sh
